services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/code
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "todoapp" ]
      interval: 1s
      timeout: 1s
      retries: 10

  redis:
    image: redis
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A app.celery.worker worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db
  beat:
    build: .
    command: celery -A app.celery.beat beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db